### ISSUE TITLE
关于自动导入日历程序的bug

### ISSUE THREAD

**Issue by gaoyimeng** [HeZean/sustis#1]
课表中如果存在生物学原理这门课 由于周数的表示出现了“13,15”周，在识别课程结束周数转换成int的时候会报错
<img width="1440" alt="截屏2022-09-07 20 56 53" src="https://user-images.githubusercontent.com/20477521/188893119-8005a8f2-cc34-4356-be8c-a5de44d947fe.png">

**Comment by HeZean** [comment]
@gaoyimeng 感谢反馈这个问题呀，我换了个接口获取数据，用我自己的账号测试是没问题了，你可以下载最新版本的代码到本地运行一下，要是还有问题可以再开issue
